# Generated by Django 4.2.6 on 2023-10-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registerprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('password', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('email', models.EmailField(blank=True, default='sample@gmail.com', max_length=50, null=True)),
                ('log_date', models.DateField(auto_now_add=True, null=True)),
                ('log_time', models.TimeField(auto_now_add=True, null=True)),
                ('position', models.CharField(blank=True, default='User', max_length=255, null=True)),
                ('is_staff', models.IntegerField(default=0)),
                ('active_status', models.IntegerField(default=0)),
            ],
        ),
    ]
