# Generated by Django 4.2.6 on 2023-10-28 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questhub_app', '0002_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='like_answers', to='questhub_app.registerprofile')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questhub_app.questions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questhub_app.registerprofile')),
            ],
        ),
    ]
